<?php

namespace app\modules\v1\forms\userAuth;


use app\models\Auth;
use app\models\User;
use app\models\UserGroup;
use yii\base\Model;
use app\modules\v1\forms\CommonForm;

class MenuAddForm extends CommonForm
{
    public $menu_id;
    public $name;
    public $key;
    public $router;
    public $pid;
    public $sort;
    public $module;
    public $controller;
    public $action;


    public function rules()
    {
        return [
            ['menu_id','required','message'=>'menu_id不能为空'],
            ['menu_id','match','pattern'=>'/^0$/'],
            ['auth_name','required','message'=>'权限名不能为空'],
            ['module_name','required','message'=>'模块名不能为空'],
            ['auth_c','required','message'=>'控制器名不能为空'],
            ['auth_a','required','message'=>'方法名不能为空'],
            ['sort_order','required','message'=>'排序不能为空'],
            ['sort_order','match','pattern'=>'/^\d+$/'],
            ['module_name','required','message'=>'模块名不能为空'],
        ];
    }

    public function afterValidate()
    {

        parent::afterValidate(); // TODO: Change the autogenerated stub

        $auth=Auth::findOne(['module_name'=>$this->module_name,'auth_c'=>$this->auth_c,'auth_a'=>$this->auth_a]);
        if($auth){
            $this->addError("module_name","模块,控制器,方法存在完全一样的记录");
            return false;
        }



    }

    //
    public function save(){


        $obj= new Auth();
        $obj->auth_id=$this->auth_id;
        $obj->auth_name=$this->auth_name;
        $obj->module_name=$this->module_name;
        $obj->auth_c=$this->auth_c;
        $obj->auth_a=$this->auth_a;
        $obj->sort_order=$this->sort_order;
        $obj->save(false);

    }

}